### ISSUE TITLE
CRUD queries for each app

### ISSUE THREAD

**Issue by Nabajyoti4** [saqibur/django-project-structure#14]
Your project structure appears to be well-organized and promising, and I appreciate the effort put into it. I have a question regarding managing database queries efficiently across the application. We often need to write multiple queries and wish to centralize them for reuse within the app or even in other apps in the project

My suggestion is to create a crud folder within the app directory and organize files based on the tables used in the application. Within each file, you can define a class like PostCRUD:

Class PostCRUD:
     def get()
     
     def create()
     
     
This approach allows for a systematic organization of database operations, ensuring that queries are centralized and can be easily reused throughout the application or in other projects. It promotes modularity and maintainability, enabling efficient development and scalability.

please suggest any other better approach if you have

**Comment by saqibur** [comment]
@Nabajyoti4 - that's a nice suggestion.

Just to add, I think you'll find that `services.py` for each app in your Django project pretty much serves that purpose. Let's say you have a `Post` model, and therefore create a `PostService` - you can then define all CRUD operations in that service, alongside any other functionality you desire.

You'll notice in the `README.md` that you can define either model managers (a.k.a fatty-models) or services to handle CRUD and muc more. So you can really go either way.

Let me know if you have more questions! Thanks.

**Comment by saqibur** [comment]
To cleary define an example:

```python
class PostService:
    def create(self):
        pass

    def update(self):
        pass

    def delete(self):
        pass

    def retrieve(self):
        pass
```
